# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowinfo',
            name='monitor_point',
        ),
        migrations.RemoveField(
            model_name='sampleinfo',
            name='monitor_point',
        ),
        migrations.DeleteModel(
            name='FlowInfo',
        ),
        migrations.DeleteModel(
            name='MonitorPoint',
        ),
        migrations.DeleteModel(
            name='SampleInfo',
        ),
    ]
