# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0003_auto_20190319_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorpoint',
            name='work_function',
            field=models.IntegerField(verbose_name='监测方法'),
        ),
    ]
