# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0003_auto_20190320_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowinfo',
            name='canal_width',
            field=models.FloatField(max_length=32, null=True, verbose_name='渠宽'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='cicle_instantaneous_flow_rate1',
            field=models.FloatField(max_length=32, null=True, verbose_name='瞬时流速1'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='cicle_instantaneous_flow_rate2',
            field=models.FloatField(max_length=32, null=True, verbose_name='瞬时流速2'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='cicle_instantaneous_flow_rate3',
            field=models.FloatField(max_length=32, null=True, verbose_name='瞬时流速3'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='cicle_lequid_level1',
            field=models.FloatField(max_length=32, null=True, verbose_name='液位1'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='cicle_lequid_level2',
            field=models.FloatField(max_length=32, null=True, verbose_name='液位2'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='cicle_lequid_level3',
            field=models.FloatField(max_length=32, null=True, verbose_name='液位3'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='diameter',
            field=models.FloatField(max_length=32, null=True, verbose_name='管径'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='machine_flow',
            field=models.FloatField(max_length=32, null=True, verbose_name='仪器监测流量'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='mud_depth',
            field=models.FloatField(max_length=32, null=True, verbose_name='淤泥深度'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='square_instantaneous_flow_rate1',
            field=models.FloatField(max_length=32, null=True, verbose_name='瞬时流速1'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='square_instantaneous_flow_rate2',
            field=models.FloatField(max_length=32, null=True, verbose_name='瞬时流速2'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='square_instantaneous_flow_rate3',
            field=models.FloatField(max_length=32, null=True, verbose_name='瞬时流速3'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='square_lequid_level1',
            field=models.FloatField(max_length=32, null=True, verbose_name='液位1'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='square_lequid_level2',
            field=models.FloatField(max_length=32, null=True, verbose_name='液位2'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='square_lequid_level3',
            field=models.FloatField(max_length=32, null=True, verbose_name='液位3'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='time1',
            field=models.FloatField(max_length=32, null=True, verbose_name='监测时长1'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='time2',
            field=models.FloatField(max_length=32, null=True, verbose_name='监测时长2'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='time3',
            field=models.FloatField(max_length=32, null=True, verbose_name='监测时长3'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='volume1',
            field=models.FloatField(max_length=32, null=True, verbose_name='监测水量1'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='volume2',
            field=models.FloatField(max_length=32, null=True, verbose_name='监测水量2'),
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='volume3',
            field=models.FloatField(max_length=32, null=True, verbose_name='监测水量3'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='exterior_photo',
            field=models.CharField(max_length=128, null=True, verbose_name='外景照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='machine_photo',
            field=models.CharField(max_length=128, null=True, verbose_name='仪器照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='not_monitor_reason',
            field=models.CharField(max_length=128, null=True, verbose_name='无法监测原因'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='probe_photo',
            field=models.CharField(max_length=128, null=True, verbose_name='探头照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='setup_photo',
            field=models.CharField(max_length=128, null=True, verbose_name='仪器设置照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='status_photo',
            field=models.CharField(max_length=128, null=True, verbose_name='监测点现状照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='water_flow_photo',
            field=models.CharField(max_length=128, null=True, verbose_name='水流照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='work_photo',
            field=models.CharField(max_length=128, null=True, verbose_name='工作照'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='AFVO',
            field=models.CharField(max_length=32, null=True, verbose_name='动植物油'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='AIS',
            field=models.CharField(max_length=32, null=True, verbose_name='阴离子表面活性剂'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='BOD',
            field=models.CharField(max_length=32, null=True, verbose_name='五日生化需氧量'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='COD',
            field=models.CharField(max_length=32, null=True, verbose_name='化学需氧量'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='CR',
            field=models.CharField(max_length=32, null=True, verbose_name='透明度'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='Cyanide',
            field=models.CharField(max_length=32, null=True, verbose_name='氰化物'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='DO',
            field=models.CharField(max_length=32, null=True, verbose_name='溶解氧'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='FLOW',
            field=models.CharField(max_length=32, null=True, verbose_name='流量'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='NH3_N',
            field=models.CharField(max_length=32, null=True, verbose_name='氨氮'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='ORP',
            field=models.CharField(max_length=32, null=True, verbose_name='氧化还原电位'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='SS',
            field=models.CharField(max_length=32, null=True, verbose_name='悬浮物'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='SinkableS',
            field=models.CharField(max_length=32, null=True, verbose_name='易沉固体'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='Sulfide',
            field=models.CharField(max_length=32, null=True, verbose_name='硫化物'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='TN',
            field=models.CharField(max_length=32, null=True, verbose_name='总氮'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='TP',
            field=models.CharField(max_length=32, null=True, verbose_name='总磷'),
        ),
    ]
