# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0005_auto_20190321_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowinfo',
            name='monitor_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='ding_callback.MonitorPoint'),
        ),
    ]
