# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0006_auto_20190325_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpoint',
            name='people',
            field=models.CharField(max_length=32, null=True, verbose_name='监测者'),
        ),
    ]
