# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0008_auto_20190327_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpoint',
            name='start_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=32, verbose_name='开始监测日期'),
            preserve_default=False,
        ),
    ]
