# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0009_monitorpoint_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorpoint',
            name='start_time',
            field=models.DateField(max_length=32, verbose_name='开始监测日期'),
        ),
    ]
