# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0010_auto_20190327_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfo',
            name='monitor_task',
            field=models.CharField(default=('SS', 'COD', 'NH3-N', 'TP', 'TN'), max_length=128, verbose_name='检测项目'),
            preserve_default=False,
        ),
    ]
