# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0011_sampleinfo_monitor_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfo',
            name='sample_count',
            field=models.IntegerField(default=2, verbose_name='样品数量'),
            preserve_default=False,
        ),
    ]
