# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_callback', '0012_sampleinfo_sample_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorpoint',
            name='exterior_photo',
            field=models.CharField(max_length=1024, null=True, verbose_name='外景照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='machine_photo',
            field=models.CharField(max_length=1024, null=True, verbose_name='仪器照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='probe_photo',
            field=models.CharField(max_length=1024, null=True, verbose_name='探头照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='setup_photo',
            field=models.CharField(max_length=1024, null=True, verbose_name='仪器设置照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='status_photo',
            field=models.CharField(max_length=1024, null=True, verbose_name='监测点现状照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='water_flow_photo',
            field=models.CharField(max_length=1024, null=True, verbose_name='水流照'),
        ),
        migrations.AlterField(
            model_name='monitorpoint',
            name='work_photo',
            field=models.CharField(max_length=1024, null=True, verbose_name='工作照'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='sample_photo',
            field=models.CharField(max_length=1024, verbose_name='样品照'),
        ),
    ]
